### ISSUE TITLE
Invalid escape pattern used

### ISSUE THREAD

**Issue by MrSeccubus** [uforia/MatterBot#32]
**Describe the bug**
You use this line in a lot of your code, but it is incorrect:
```
stripchars = '`\[\]\'\"'
```

It results in this warning:
```
feed.py:36: SyntaxWarning: invalid escape sequence '\['
  stripchars = '`\[\]\'\"'
```

Python translates this string to 
```
`[]'"
```
While I think you intended it to be translated to:
```
`\[\]'"
```
Which escapes the square brackets in regular espression.

The correct line is:
```
stripchars = '`\\[\\]\'\"'
```

**To Reproduce**
```
% (cd modules/bruceschneier/;python feed.py)
```

**Expected behavior**
stripchars should be a valid regex that catches the quare brackets `[]`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by uforia** [comment]
Thank you! Corrected and merged.
